[package]
name = "natxnekk/sessionkit"
description = "Simple ProfileStore wrapper to make replicating data easier"
version = "0.1.0"
license = "MIT"
authors = ["Natt <natt@natt.cloud>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml", "LICENSE"]

[dependencies]
bytenet = "elitriare/bytenet-max@0.2.7"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"